### ISSUE TITLE
Reproducing retrieval evaluation

### ISSUE THREAD

**Issue by roman-bushuiev** [YuanyueLi/SpectralEntropy#9]
Hello! I would like to reproduce the evaluation reported in your [paper](https://www.nature.com/articles/s41592-021-01331-z) and extend it with some new methods. However, I am puzzled by your definition of the binary classification metrics, and I would greatly appreciate your clarification.

I understand that for each spectrum, you define a set of candidate spectra for retrieval based on the first block of the corresponding InChI keys. According to the paper, if we denote a subset of retrieved InChI keys (for a certain similarity threshold) as S and a query InChI key as q:

- A `true-positive` prediction means that q belongs to S.
- A `false-positive` prediction means that q does not belong to S and S is not empty.

Following the same logic, I assume that a `true-negative` indicates that S is empty. However, I am struggling to understand what exactly a `false-negative` implies. Could you please explain your concept of a negative class and the definitions of `true-negative` and `false-negative` predictions?

Thank you in advance!

**Comment by YuanyueLi** [comment]
Hello!

Sorry that I can't understand your question. I guess you are asking how did I make the ROC curve? what I did is that:

1. For all 25,55,973 pairs of MS/MS spectra, calculate the similarity score for all pairs. Meanwhile we can also know whether each pair of MS/MS spectra belong to the same molecule or not.
2. Use 0.99 as cutoff, all pairs with similarity higher than 0.99 are considered as positive, then we can calculate the true positive and false positive, also the TPR and FPR.
3. Use 0.98 as cutoff, calculate the TPR and FPR.
4. Use 0.97 as cutoff, ……
5. Then we will have multiple TPR-FPR pairs, put them into an axis, you can get multiple dots, draw a line to connect those dots, you can get the ROC curve.
6. Calculate the AUC with the ROC curve.

Hope this can help you.

**Comment by roman-bushuiev** [comment]
Thank you for the explanation! Now it is clear.

**Comment by YuanyueLi** [comment]
Hello,

After double-checking, I found I made a mistake when I explained the workflow for creating the ROC curve. I have now updated the previous reply. Additionally, I uploaded an example code for better understanding.

You can find the benchmark code here:

https://github.com/YuanyueLi/SpectralEntropy/blob/1bea841a2bdec272a2356a31acb5498bfc59ecf0/example_for_benchmark.ipynb

**Comment by roman-bushuiev** [comment]
Thank you! 👍
